name: Split Tracks in Batches

on:
  workflow_dispatch:  # Allow manual runs
  # schedule:
  #   - cron: '0 0 * * *'    # Run batch 1 daily at 00:00 UTC
  #   - cron: '0 6 * * *'    # Run batch 2 daily at 06:00 UTC
  #   - cron: '0 12 * * *'   # Run batch 3 daily at 12:00 UTC
  #   - cron: '0 18 * * *'   # Run batch 4 daily at 18:00 UTC

jobs:
  split-tracks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [batch_1, batch_2]  # 2 processes for each scheduled time

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4  # Specify Poetry version if necessary

      - name: Install dependencies
        run: poetry install

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Set up Google Drive credentials
        env:
          CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS_JSON }}
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
        run: |
          echo "$CLIENT_SECRETS" > client_secrets.json
          echo "$GOOGLE_DRIVE_TOKEN" > token.json
          # touch token.json

      - name: Run batch split script
        run: |          
          # Run the split_files.py script with batch argument
          poetry run python split_tracks.py --batch ${{ matrix.batch }}
